### ISSUE TITLE
libqrencode 4 is out.

### ISSUE THREAD

**Issue by tmtvl** [frithnanth/perl6-Image-QRCode#3]
Hey, my local version of libqrencode is v4, I've got an updated version on my fork. Should I make a PR or would you like to keep support for v3 for the time being?

**Comment by frithnanth** [comment]
I'm on vacation now, I can look into this in a couple of weeks. In any case a PR is welcome; I will tag the present version as the last supporting v3.

**Comment by frithnanth** [comment]
I've just uploaded a new version to the CPAN.
Since libqrencode v3 and v4 are API-compatible, my module defaults to v4, but can work with v3 as well (see documentation, section `Prerequisites`)
Thank you for pointing me out to the new version!
